# Generated by Django 5.2.7 on 2025-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_booking_contact_address_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed specs (e.g. camera, battery, lens, etc)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/'),
        ),
    ]
