# Generated by Django 5.2.7 on 2025-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_details_asset_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_datetime'], 'permissions': [('can_accept_booking', 'Can accept booking'), ('can_reject_booking', 'Can reject booking'), ('can_cancel_booking', 'Can cancel booking')]},
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
