# Generated by Django 5.2.7 on 2026-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
