# Generated by Django 5.2.7 on 2026-01-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Cancellation Request',
                'verbose_name_plural': 'Cancellation Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.booking',),
        ),
    ]
