# Generated by Django 4.2.1 on 2026-01-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_category_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='received_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/received/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='returned_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/returned/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled'), ('received', 'Received'), ('returned', 'Returned')], default='pending', max_length=50),
        ),
    ]
