# Generated by Django 4.2.1 on 2026-01-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_booking_received_image_booking_returned_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
