# Generated by Django 4.2.1 on 2026-02-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_booking_received_at_booking_returned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.subcategory'),
        ),
    ]
