# Generated by Django 4.2.1 on 2026-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_subcategory_asset_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
